name: 'Trigger on PR comment'
on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]
jobs:
  printing: 
    name: just print
    runs-on: [ubuntu-latest]
    
    steps:
      - name: huh
        if: ${{ github.event_name == 'issue_comment' && github.event.action == 'created' && github.event.comment.body == 'trigger_on_me' }}
        run: echo This is comment exec.
